# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: argocd
  finalizers:
  - openreplay.com/cluster
  labels:
    name: rajesh
    domain: rajesh.com
    openreplay.com/ownerOf: "Cluster"
type: Opaque
data:
---
