# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argofin
    app.kubernetes.io/managed-by: kustomize
  name: cleaner-viewer-role
rules:
- apiGroups:
  - argoproj.io
  - ""
  resources:
  - applications
  - applicationsets
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  - ""
  resources:
  - applications/status
  - applicationsets/status
  - secrets/status
  verbs:
  - get
