# permissions for end users to edit applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argofin
    app.kubernetes.io/managed-by: kustomize
  name: cleaner-editor-role
rules:
- apiGroups:
  - argoproj.io
  - corev1
  resources:
  - applications
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications/status
  verbs:
  - get
