---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  - argoproj.io
  resources:
  - applications
  - applicationsets
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - argoproj.io
  resources:
  - applications/finalizers
  - applicationsets/finalizers
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  - argoproj.io
  resources:
  - applications/status
  - applicationsets/status
  - secrets/status
  verbs:
  - get
  - patch
  - update
